### ISSUE TITLE
not valid JSON file

### ISSUE THREAD

**Issue by aolko** [FHannes/IPBLoginAuth#2]
Fatal error: Uncaught exception 'Exception' with message '/var/www/[???]/data/www/wiki.tv-hub.ru/extensions/IPBLoginAuth/extension.json is not a valid JSON file.

_mediawiki 1.28_

**Comment by eschultz** [comment]
I had the same issue.  I fixed it by deleting the first open curly bracket {  and re-typing it in extension.json.

There is a UTF-8 hidden character at the beginning of the file that's causing this and by re-creating the  { character helps get rid of that

**Comment by FHannes** [comment]
I've re-encoded the file and replaced the first character, hopefully that resolves the issue.
